name: apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install requirements for documentation generation
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install .[docs]

    - name: Generate API documentation with pydoctor
      run: |

        # Run simple pydoctor build
        pydoctor \
            --project-name=docstring_parser \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="." \
            --docformat=restructuredtext \
            --privacy="HIDDEN:docstring_parser.tests" \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./docstring_parser

    - name: Push API documentation to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate API documentation"
